Fix persistence of linked extent slider
ebu/ear-production-suite pull request #17
Opened 2020-10-20 11:25 UTC by rsjtaylor

fixes #3

2021-01-22 17:22 UTC, firthm01 requested changes
There still seems to be a bug here. Steps to reproduce:

- put an object plugin on a track and open it.
- set size to something (link will be on by default)
- click to unlink size
- set width, height, depth to different values.
- close the plugin and reopen it

- width, height and depth have reset to the same value as size.

2021-01-22 17:40 UTC, firthm01 commented
I've noticed that the parameter values are correct (looking at VST in non-UI mode after reopening) - it's just the GUI that is showing the wrong values. It seems to restore them from `cachedWidth_` et al, which seem to have stored the wrong value (size value, not width). Not sure on the purpose of those cached vars... shouldn't we just pull through parameter values from the processor when we need to update GUI state?

2021-07-14 15:42 UTC, rsjtaylor commented
> I've noticed that the parameter values are correct (looking at VST in non-UI mode after reopening) - it's just the GUI that is showing the wrong values. It seems to restore them from `cachedWidth_` et al, which seem to have stored the wrong value (size value, not width). Not sure on the purpose of those cached vars... shouldn't we just pull through parameter values from the processor when we need to update GUI state?

I can't reproduce this on macos or windows, could you try installing the build artefacts from this & see if the issue has gone now? Guess it might have been fixed by changes in the interim.

2021-07-19 15:57 UTC, firthm01 approved these changes

2021-07-20 11:24 UTC, merged