Fix #87 Scene appears to delete wrong item
ebu/ear-production-suite pull request #97
Opened 2021-07-29 16:44 UTC by firthm01

Closes #87 

`ElementViewList` maintained a `std::vector<ElementView*> elements_;`, and `ElementsContainer` also maintained a `std::vector<std::shared_ptr<ElementView>> elements;` - these could get out of sync, and hence why the UI appeared to be deleting the wrong item.

The easy fix would have been to modify the `JuceSceneFrontendConnector::elementMoved` method to ensure it updates the ordering of vector elements in the `ElementViewList` (which it already did) **AND** the vector of elements in `ElementsContainer` such that the indices always matched and operations were always enacted on the correct vector elements.

However, it seemed redundant to me to be maintaining two vectors. It seems much more logical to just use the vector in `ElementsContainer`, and all operations concerning adding, moving and removing elements to be handled by `ElementsContainer` (this also meant moving the listeners to `ElementsContainer` too).

2021-08-10 11:31 UTC, rsjtaylor requested changes
Looks good, could you rebase on top of main & squash to maybe 2 commits (1 for the actual fix, one for the refactor?).

2021-08-11 16:30 UTC, firthm01 commented on ear-production-suite/plugins/scene/src/elements_container.hpp
>    std::unique_ptr<ElementViewList> list;
Ah good spot!

2021-08-11 16:52 UTC, firthm01 commented
> Looks good, could you rebase on top of main & squash to maybe 2 commits (1 for the actual fix, one for the refactor?).

Rebase done and the changes requested.

Not sure I understand what you mean by squashing to a fix commit and a refactor commit. Really, there wasn't a fix as such - the refactor removed the issue (using only one vector, so no need to synchronise them)

2021-08-12 10:25 UTC, rsjtaylor approved these changes

2021-08-12 10:34 UTC, merged